insert into booking (booking) values ('Calypso');
insert into booking (booking) values ('Sauthoff');
insert into booking (booking) values ('Fair Oaks');
insert into booking (booking) values ('Anthes');
insert into booking (booking) values ('Northfield');
insert into booking (booking) values ('Hudson');
insert into booking (booking) values ('Haas');
insert into booking (booking) values ('Hanson');
insert into booking (booking) values ('Harbort');
insert into booking (booking) values ('Magdeline');